### ISSUE TITLE
Add a program option to specify a file with all include/exclude paths

### ISSUE THREAD

**Issue by FelixPetriconi** [dsuni/svndumpsanitizer#14]
For my current task I have to filter a huge bunch of paths from an existing huge repository so I would like to specify the filter-paths through a file as it is possible for svndumpfilter.

I have already done all necessary changes and I would like to test the changes so that I can send a push-request. How can I run the tests? Btw. it seems to me that I need a test repository, or am I on the wrong track?

**Comment by FelixPetriconi** [comment]
I figured out in the meantime that on Mac the dialect of sed is different to make the tests run.

**Comment by katef** [comment]
I'd love this, too :) The diff in #15 looks great to me!

**Comment by dsuni** [comment]
I didn't implement this because it's quite easy to achieve on the command line without actually doing anything with svndumpsanitizer. Running:
svndumpsanitizer --include `cat file_with_includes.txt | tr '\n' ' '` ...
should achieve the same thing.

**Comment by katef** [comment]
@dsuni thank you for making this program, by the way! it's what I wanted svnfilter to be :)

**Comment by RockyMM** [comment]
@dsuni then, this issue can be closed? @FelixPetriconi I assume you have managed?

**Comment by t-anc** [comment]
This solution doesn't work for big lists ;) 
However https://github.com/dsuni/svndumpsanitizer/pull/15 worked for me (~500k lines).
Thank you !
