### ISSUE TITLE
spurious Test: lines at the top of the output

### ISSUE THREAD

**Issue by reinierpost** [dsuni/svndumpsanitizer#16]
[remove-spurious-printf.diff.txt](https://github.com/dsuni/svndumpsanitizer/files/2005600/remove-spurious-printf.diff.txt)

I ran svndumpsanitizer on my dump, and the resulting dump refused to svnadmin load.
It turns out it started with a couple of lines starting with 'Test: '
Without them, the dump loaded fine.

The culprit is the following statement on line `svndumpsanitizer.c:1543`:

         printf("Test: %s %s %s\n", temp_str, revisions[i].nodes[j].path, redefined_root);

Why not just remove it?

**Comment by dsuni** [comment]
D'oh! Line deleted. Thanks for pointing it out.
