### ISSUE TITLE
Tag releases 

### ISSUE THREAD

**Issue by SuperSandro2000** [dsuni/svndumpsanitizer#22]
Tagging commits that bump the version number (eg https://github.com/dsuni/svndumpsanitizer/commit/cbf917c000ee42fbb31a8667014a4357bbfdd6a6) make it so much easier for distros to package this tool and staying up to date on new versions and utilizing existing infrastructure to create those updates.

**Comment by dsuni** [comment]
Tags added for v2.0.0 and upwards.
