### ISSUE TITLE
dumpsanitizer struck

### ISSUE THREAD

**Issue by Cypselus** [dsuni/svndumpsanitizer#7]
Hi,
got troubles sanitizing one of repositories (57 000 revisions), about 50 paths in "include" parameter.

sanitized repository dump works pretty well:
$ time ./svndumpsanitizer --infile stripped --outfile sripped.sanitized -d --include trunk  ...
<cut>
Step 7/7: Adding revision deleting surplus nodes... NOT NEEDED
real    1m49.972s
user    1m48.283s
sys     0m0.540s

but original full dump is being proceed for about 37 hours with 100% CPU usage
Step 1/7: Reading the infile... OK
Step 2/7: Removing unwanted nodes...                                                                                                                                             

It's not the biggest repository I've already filtered:
7.2G dump
455M stripped
95M stripped.sanitized

Have not found direct contact emal, unfortunatelly. Please contact me if you are interested in any additional information.

Looking forward to,
Evgeny

**Comment by dsuni** [comment]
Nothin on this for a couple of months. Assuming case closed.
